Build glfw with shared libraries
Avoids the following error on NixOS:

[ 17%] Linking CXX executable ../bin/12-simplecompute
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: /nix/store/swmqxvi3kwid1s5landsyc56lvj4gxiq-libX11-1.6.12/lib/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/12-simplecompute.dir/build.make:106: ../bin/12-simplecompute] Error 1
make[1]: *** [CMakeFiles/Makefile2:312: CMakeFiles/12-simplecompute.dir/all] Error 2
make: *** [Makefile:149: all] Error 2